In [ ]:
import pandas as pd
import geopandas as gpd
import os
import glob

In [2]:
df_census = pd.read_csv('census.csv', index_col=0)
df_census

,geography,years,pop_females_heavy_drinking,pop_females_heavy_drinking_12_to_17_years,pop_females_heavy_drinking_18_to_34_years,pop_females_heavy_drinking_35_to_49_years,pop_females_heavy_drinking_50_to_64_years_,pop_females_heavy_drinking_65_years_and_over,pop_male_heavy_drinking,pop_heavy_drinking_males_12_to_17_years,...,12_to_17_years_male,18_to_34_years_male,35_to_49_years_male,50_to_64_years_male,65_years_and_above_male,12_to_17_years_female,18_to_34_years_female,35_to_49_years_female,50_to_64_years_female,65_years_and_above_female
0,Alberta,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,144591.0,521227.0,431221.0,374601.0,193876.0,136108.0,497403.0,406306.0,357020.0,232176.0
1,Alberta,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,145162.0,537678.0,438725.0,385787.0,204204.0,136591.0,509142.0,413041.0,368773.0,241743.0
2,Alberta,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,145734.0,553552.0,445620.0,395985.0,213455.0,137479.0,519904.0,421665.0,379760.0,250594.0
3,Alberta,2015,241300.0,NaN,132100.0,54400.0,39200.0,9900.0,406400.0,NaN,...,147059.0,558985.0,448080.0,400919.0,222587.0,140149.0,523422.0,429020.0,387457.0,259280.0
4,Alberta,2016,230700.0,NaN,110500.0,57800.0,52500.0,7200.0,435800.0,NaN,...,149473.0,552302.0,450728.0,402376.0,232614.0,142674.0,520189.0,436378.0,392641.0,269487.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,Yukon,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1270.0,4828.0,4115.0,4611.0,2408.0,1220.0,4753.0,4367.0,4456.0,2168.0
126,Yukon,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1282.0,4919.0,4288.0,4550.0,2598.0,1206.0,4897.0,4463.0,4436.0,2340.0
127,Yukon,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1306.0,4945.0,4415.0,4436.0,2802.0,1241.0,4956.0,4608.0,4398.0,2540.0
128,Yukon,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1380.0,4950.0,4519.0,4336.0,2997.0,1253.0,5072.0,4772.0,4299.0,2761.0
129,Yukon,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1448.0,5066.0,4675.0,4265.0,3214.0,1273.0,5176.0,4927.0,4276.0,2977.0

In [3]:
df_census.rename(columns={'years':'year', 'geography':'state_name'}, inplace=True)
df_census.head(5)

,state_name,year,pop_females_heavy_drinking,pop_females_heavy_drinking_12_to_17_years,pop_females_heavy_drinking_18_to_34_years,pop_females_heavy_drinking_35_to_49_years,pop_females_heavy_drinking_50_to_64_years_,pop_females_heavy_drinking_65_years_and_over,pop_male_heavy_drinking,pop_heavy_drinking_males_12_to_17_years,...,12_to_17_years_male,18_to_34_years_male,35_to_49_years_male,50_to_64_years_male,65_years_and_above_male,12_to_17_years_female,18_to_34_years_female,35_to_49_years_female,50_to_64_years_female,65_years_and_above_female
0,Alberta,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,144591.0,521227.0,431221.0,374601.0,193876.0,136108.0,497403.0,406306.0,357020.0,232176.0
1,Alberta,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,145162.0,537678.0,438725.0,385787.0,204204.0,136591.0,509142.0,413041.0,368773.0,241743.0
2,Alberta,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,145734.0,553552.0,445620.0,395985.0,213455.0,137479.0,519904.0,421665.0,379760.0,250594.0
3,Alberta,2015,241300.0,NaN,132100.0,54400.0,39200.0,9900.0,406400.0,NaN,...,147059.0,558985.0,448080.0,400919.0,222587.0,140149.0,523422.0,429020.0,387457.0,259280.0
4,Alberta,2016,230700.0,NaN,110500.0,57800.0,52500.0,7200.0,435800.0,NaN,...,149473.0,552302.0,450728.0,402376.0,232614.0,142674.0,520189.0,436378.0,392641.0,269487.0

In [4]:
gdf_shape = gpd.read_file('../../geo_boundaries/CAN/lpr_000b21a_e.shp')
gdf_shape

,PRUID,DGUID,PRNAME,PRENAME,PRFNAME,PREABBR,PRFABBR,LANDAREA,geometry
0,10,2021A000210,Newfoundland and Labrador / Terre-Neuve-et-Lab...,Newfoundland and Labrador,Terre-Neuve-et-Labrador,N.L.,T.-N.-L.,3.581704e+05,"MULTIPOLYGON (((8841194.729 2213093.663, 88411..."
1,11,2021A000211,Prince Edward Island / Île-du-Prince-Édouard,Prince Edward Island,Île-du-Prince-Édouard,P.E.I.,Î.-P.-É.,5.681179e+03,"MULTIPOLYGON (((8374335.443 1629502.597, 83743..."
2,12,2021A000212,Nova Scotia / Nouvelle-Écosse,Nova Scotia,Nouvelle-Écosse,N.S.,N.-É.,5.282471e+04,"MULTIPOLYGON (((8310463.217 1250722.263, 83104..."
3,13,2021A000213,New Brunswick / Nouveau-Brunswick,New Brunswick,Nouveau-Brunswick,N.B.,N.-B.,7.124850e+04,"MULTIPOLYGON (((7964100.720 1576822.289, 79641..."
4,24,2021A000224,Quebec / Québec,Quebec,Québec,Que.,Qc,1.298600e+06,"MULTIPOLYGON (((6948393.211 2760814.626, 69483..."
5,35,2021A000235,Ontario,Ontario,Ontario,Ont.,Ont.,8.924118e+05,"MULTIPOLYGON (((7146731.034 1071348.914, 71467..."
6,46,2021A000246,Manitoba,Manitoba,Manitoba,Man.,Man.,5.403102e+05,"MULTIPOLYGON (((6036427.023 2552091.071, 60364..."
7,47,2021A000247,Saskatchewan,Saskatchewan,Saskatchewan,Sask.,Sask.,5.770604e+05,"POLYGON ((5248633.914 2767057.263, 5249285.640..."
8,48,2021A000248,Alberta,Alberta,Alberta,Alta.,Alb.,6.346583e+05,"POLYGON ((5228304.177 2767597.891, 5228098.463..."
9,59,2021A000259,British Columbia / Colombie-Britannique,British Columbia,Colombie-Britannique,B.C.,C.-B.,9.206866e+05,"MULTIPOLYGON (((3843551.097 2389750.100, 38435..."
10,60,2021A000260,Yukon,Yukon,Yukon,Y.T.,Yn,4.723454e+05,"MULTIPOLYGON (((4573723.537 4214993.163, 45737..."
11,61,2021A000261,Northwest Territories / Territoires du Nord-Ouest,Northwest Territories,Territoires du Nord-Ouest,N.W.T.,T.N.-O.,1.127712e+06,"MULTIPOLYGON (((5484328.789 3866905.254, 54843..."
12,62,2021A000262,Nunavut,Nunavut,Nunavut,Nvt.,Nt,1.836994e+06,"MULTIPOLYGON (((6990267.260 1768670.111, 69902..."

In [5]:
df_census = df_census.merge(gdf_shape[['PRENAME','PREABBR']], how='left', left_on='state_name', right_on='PRENAME').drop(columns=['PRENAME']).rename(columns={'PREABBR':'state_code'})

In [6]:
df_census.shape
# 130 rows × 209 columns

(130, 209)

In [7]:
cols_rename = ['total_births',
                'live_births',
                'fetal_deaths_(stillbirths)',
                'perinatal_deaths_by_year',
                '13_to_19_years',
                '20_to_34_years',
                '35_to_49_years',
                '50_years_and_above',
                '12_to_17_years',
                '18_to_34_years',
                '50_to_64_years',
                '65_years_and_above',
                '12_to_17_years_male',
                '18_to_34_years_male',
                '35_to_49_years_male',
                '50_to_64_years_male',
                '65_years_and_above_male',
                '12_to_17_years_female',
                '18_to_34_years_female',
                '35_to_49_years_female',
                '50_to_64_years_female',
                '65_years_and_above_female',
                'pop_females_heavy_drinking',
                'pop_females_heavy_drinking_12_to_17_years',
                'pop_females_heavy_drinking_18_to_34_years',
                'pop_females_heavy_drinking_35_to_49_years',
                'pop_females_heavy_drinking_50_to_64_years_',
                'pop_females_heavy_drinking_65_years_and_over',
                'pop_male_heavy_drinking',
                'pop_heavy_drinking_males_12_to_17_years',
                'pop_heavy_drinking_males_18_to_34_years',
                'pop_heavy_drinking_males_35_to_49_years',
                'pop_heavy_drinking_males_50_to_64_years',
                'pop_heavy_drinking_males_65_years_and_over',
                'pop_heavy_drinking',
                'pop_heavy_drinking_12_to_17_years',
                'pop_heavy_drinking_18_to_34_years',
                'pop_heavy_drinking_35_to_49_years',
                'pop_heavy_drinking_50_to_64_years',
                'pop_heavy_drinking_65_years_and_over'
              ]
obj = {}
for c in cols_rename:
    for k in ['births','deaths','years','heavy_drinking']:
        if k in c:
            obj[c] = f"{k}_{c.replace(f'_{k}','')}"

df_census.rename(columns=obj, inplace=True)
df_census

,state_name,year,heavy_drinking_pop_females,heavy_drinking_pop_females_12_to_17_years,heavy_drinking_pop_females_18_to_34_years,heavy_drinking_pop_females_35_to_49_years,heavy_drinking_pop_females_50_to_64_years_,heavy_drinking_pop_females_65_years_and_over,heavy_drinking_pop_male,heavy_drinking_pop_males_12_to_17_years,...,years_18_to_34_male,years_35_to_49_male,years_50_to_64_male,years_65_and_above_male,years_12_to_17_female,years_18_to_34_female,years_35_to_49_female,years_50_to_64_female,years_65_and_above_female,state_code
0,Alberta,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,521227.0,431221.0,374601.0,193876.0,136108.0,497403.0,406306.0,357020.0,232176.0,Alta.
1,Alberta,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,537678.0,438725.0,385787.0,204204.0,136591.0,509142.0,413041.0,368773.0,241743.0,Alta.
2,Alberta,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,553552.0,445620.0,395985.0,213455.0,137479.0,519904.0,421665.0,379760.0,250594.0,Alta.
3,Alberta,2015,241300.0,NaN,132100.0,54400.0,39200.0,9900.0,406400.0,NaN,...,558985.0,448080.0,400919.0,222587.0,140149.0,523422.0,429020.0,387457.0,259280.0,Alta.
4,Alberta,2016,230700.0,NaN,110500.0,57800.0,52500.0,7200.0,435800.0,NaN,...,552302.0,450728.0,402376.0,232614.0,142674.0,520189.0,436378.0,392641.0,269487.0,Alta.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,Yukon,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4828.0,4115.0,4611.0,2408.0,1220.0,4753.0,4367.0,4456.0,2168.0,Y.T.
126,Yukon,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4919.0,4288.0,4550.0,2598.0,1206.0,4897.0,4463.0,4436.0,2340.0,Y.T.
127,Yukon,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4945.0,4415.0,4436.0,2802.0,1241.0,4956.0,4608.0,4398.0,2540.0,Y.T.
128,Yukon,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4950.0,4519.0,4336.0,2997.0,1253.0,5072.0,4772.0,4299.0,2761.0,Y.T.
129,Yukon,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5066.0,4675.0,4265.0,3214.0,1273.0,5176.0,4927.0,4276.0,2977.0,Y.T.

In [8]:
fcols = ['state_name','state_code','year']
lcols = sorted(list(set(df_census.columns) - set(fcols)))

df_census = df_census[fcols + lcols]
df_census

,state_name,state_code,year,belonging,belonging_12_to_17_years,belonging_18_to_34_years,belonging_35_to_49_years,belonging_50_to_64_years,belonging_65_years_and_over,belonging_females,...,years_35_to_49,years_35_to_49_female,years_35_to_49_male,years_50_and_above,years_50_to_64,years_50_to_64_female,years_50_to_64_male,years_65_and_above,years_65_and_above_female,years_65_and_above_male
0,Alberta,Alta.,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,837527.0,406306.0,431221.0,1157673.0,731621.0,357020.0,374601.0,426052.0,232176.0,193876.0
1,Alberta,Alta.,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,851766.0,413041.0,438725.0,1200507.0,754560.0,368773.0,385787.0,445947.0,241743.0,204204.0
2,Alberta,Alta.,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,867285.0,421665.0,445620.0,1239794.0,775745.0,379760.0,395985.0,464049.0,250594.0,213455.0
3,Alberta,Alta.,2015,2336000.0,219900.0,661500.0,601600.0,542400.0,310600.0,1180000.0,...,877100.0,429020.0,448080.0,1270243.0,788376.0,387457.0,400919.0,481867.0,259280.0,222587.0
4,Alberta,Alta.,2016,2378800.0,218400.0,671000.0,626200.0,531800.0,331400.0,1177600.0,...,887106.0,436378.0,450728.0,1297118.0,795017.0,392641.0,402376.0,502101.0,269487.0,232614.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,Yukon,Y.T.,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8482.0,4367.0,4115.0,13643.0,9067.0,4456.0,4611.0,4576.0,2168.0,2408.0
126,Yukon,Y.T.,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8751.0,4463.0,4288.0,13924.0,8986.0,4436.0,4550.0,4938.0,2340.0,2598.0
127,Yukon,Y.T.,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9023.0,4608.0,4415.0,14176.0,8834.0,4398.0,4436.0,5342.0,2540.0,2802.0
128,Yukon,Y.T.,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9291.0,4772.0,4519.0,14393.0,8635.0,4299.0,4336.0,5758.0,2761.0,2997.0
129,Yukon,Y.T.,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9602.0,4927.0,4675.0,14732.0,8541.0,4276.0,4265.0,6191.0,2977.0,3214.0

In [9]:
FN = 'CAN_all_census_stats.csv'
df_census.to_csv(FN)